export const poolsStatic = [
    {
        poolId: 0,
        logo:"https://robohash.org/0?size=50x50",
        access:'Trodl Minions',
        tokenName:'Zero',
        ticker:'ZERO',
        aboutProject:" Project Zero. Businesses across the globe are struggling to access financing as traditional finance is broken; DeFi is an alternative source, but it is not yet fully matured to a stage where it can plug the funding gap.",
        projectWebsite:"https://www.trodl.com",
        projectWhitepaper:"https://www.trodl.com",
        projectContract:"https://www.trodl.com",
        projectTwitter:"https://www.trodl.com",
        projectTelegram:"https://www.trodl.com",
        chain: "Binance Smart Chain",
        totalSupply: "600000000",
        type: "BEP-20",
        totalRaise: "$0000",
        seedPrice: "$0.04",
        privatePrice: "$0.06",
        idoPrice: "$0.07",
        launchDate: "18-11-2021",
        hardCap: "$0,000,000,000 USD",
    },
    {
        poolId: 1,
        logo:"https://robohash.org/1?size=50x50",
        access:'Trodl Monsters',
        tokenName:'One',
        ticker:'ONE',
        aboutProject:" Project One. Businesses across the globe are struggling to access financing as traditional finance is broken; DeFi is an alternative source, but it is not yet fully matured to a stage where it can plug the funding gap.",
        projectWebsite:"https://www.trodl.com",
        projectWhitepaper:"https://www.trodl.com",
        projectContract:"https://www.trodl.com",
        projectTwitter:"https://www.trodl.com",
        projectTelegram:"https://www.trodl.com",
        chain: "Binance Smart Chain",
        totalSupply: "600000000",
        type: "BEP-20",
        totalRaise: "$1000",
        seedPrice: "$0.04",
        privatePrice: "$0.06",
        idoPrice: "$0.07",
        launchDate: "18-11-2021",
        hardCap: "$1,000,000,000 USD",
        intervalSchedule : [{width: "25%", date: "1 day" }, {width: "25%", date: "2 day" }, {width: "25%", date: "3 day" }, {width: "25%", date: "4 day" }],
    },
    {
        poolId: 2,
        logo:"https://robohash.org/2?size=50x50",
        access:'Trodl Monsters',
        tokenName:'Two',
        ticker:'TWO',
        aboutProject:" Project Two. Businesses across the globe are struggling to access financing as traditional finance is broken; DeFi is an alternative source, but it is not yet fully matured to a stage where it can plug the funding gap.",
        projectWebsite:"https://www.trodl.com",
        projectWhitepaper:"https://www.trodl.com",
        projectContract:"https://www.trodl.com",
        projectTwitter:"https://www.trodl.com",
        projectTelegram:"https://www.trodl.com",
        chain: "Binance Smart Chain",
        totalSupply: "600000000",
        type: "BEP-20",
        totalRaise: "$2000",
        seedPrice: "$0.04",
        privatePrice: "$0.06",
        idoPrice: "$0.07",
        launchDate: "18-11-2021",
        hardCap: "$2,000,000,000 USD",
        linearSchedule: {immPart: "25%", unlockingEnds: "2 days", remainingPart: "75%"},
    },
    {
        poolId: 3,
        logo:"https://robohash.org/3?size=50x50",
        access:'Trodl Minions',
        tokenName:'Three',
        ticker:'THREE',
        aboutProject:" Project Three. Businesses across the globe are struggling to access financing as traditional finance is broken; DeFi is an alternative source, but it is not yet fully matured to a stage where it can plug the funding gap.",
        projectWebsite:"https://www.trodl.com",
        projectWhitepaper:"https://www.trodl.com",
        projectContract:"https://www.trodl.com",
        projectTwitter:"https://www.trodl.com",
        projectTelegram:"https://www.trodl.com",
        chain: "Binance Smart Chain",
        totalSupply: "600000000",
        type: "BEP-20",
        totalRaise: "$3000",
        seedPrice: "$0.04",
        privatePrice: "$0.06",
        idoPrice: "$0.07",
        launchDate: "22-11-2021",
        hardCap: "$3,000,000,000 USD",
    },
    {
        poolId: 4,
        logo:"https://robohash.org/4?size=50x50",
        access:'Trodl Monsters',
        tokenName:'Four',
        ticker:'FOUR',
        aboutProject:" Project Four. Businesses across the globe are struggling to access financing as traditional finance is broken; DeFi is an alternative source, but it is not yet fully matured to a stage where it can plug the funding gap.",
        projectWebsite:"https://www.trodl.com",
        projectWhitepaper:"https://www.trodl.com",
        projectContract:"https://www.trodl.com",
        projectTwitter:"https://www.trodl.com",
        projectTelegram:"https://www.trodl.com",
        chain: "Binance Smart Chain",
        totalSupply: "600000000",
        type: "BEP-20",
        totalRaise: "$4000",
        seedPrice: "$0.04",
        privatePrice: "$0.06",
        idoPrice: "$0.07",
        launchDate: "21-11-2021",
        hardCap: "$4,000,000,000 USD",
        intervalSchedule : [{width: "25%", date: "30 day" }, {width: "25%", date: "10 day" }, {width: "25%", date: "10 day" }, {width: "25%", date: "10 day" }],
    },
    {
        poolId: 5,
        logo:"https://robohash.org/5?size=50x50",
        access:'Trodl Monsters',
        tokenName:'Five',
        ticker:'Five',
        aboutProject:" Project Five. Businesses across the globe are struggling to access financing as traditional finance is broken; DeFi is an alternative source, but it is not yet fully matured to a stage where it can plug the funding gap.",
        projectWebsite:"https://www.trodl.com",
        projectWhitepaper:"https://www.trodl.com",
        projectContract:"https://www.trodl.com",
        projectTwitter:"https://www.trodl.com",
        projectTelegram:"https://www.trodl.com",
        chain: "Binance Smart Chain",
        totalSupply: "600000000",
        type: "BEP-20",
        totalRaise: "$5000",
        seedPrice: "$0.04",
        privatePrice: "$0.06",
        idoPrice: "$0.07",
        launchDate: "18-11-2021",
        hardCap: "$5,000,000,000 USD",
        linearSchedule: {immPart: "25%", unlockingEnds: "10 days", remainingPart: "75%"},
    },
];