export const poolsStatic = [
    {
        poolId: 0,
        logo:"https://robohash.org/0?size=50x50",
        access:'Test Access',
        tokenName:'Issuance Token Test',
        ticker:'IIT',
        aboutProject:" Test pool: DO NOT APPROVE or SWAP",
        projectWebsite:"https://www.trodl.com",
        projectWhitepaper:"https://www.trodl.com",
        projectContract:"https://www.trodl.com",
        projectTwitter:"https://www.trodl.com",
        projectTelegram:"https://www.trodl.com",
        chain: "Binance Smart Chain",
        totalSupply: "1000000",
        type: "BEP-20",
        totalRaise: "$1000",
        seedPrice: "$0.04",
        privatePrice: "$0.06",
        idoPrice: "$0.07",
        launchDate: "01-12-2021",
        hardCap: "$1,000,000,000 USD",
    },
];